name = "fishtank"
main = "src/index.js"
compatibility_date = "2025-01-01"

routes = [
  { pattern = "mccarrison.me/fish", zone_name = "mccarrison.me" },
  { pattern = "mccarrison.me/fish/*", zone_name = "mccarrison.me" },
]

[vars]
PATH_PREFIX = "/fish"

[assets]
directory = "../dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
